//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Fusion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Fusion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected at least one file to commit and push.
        /// </summary>
        internal static string AtLeastOneFileExpected {
            get {
                return ResourceManager.GetString("AtLeastOneFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token with purpose AutoCommitPush not found.
        /// </summary>
        internal static string AutoCommitPushAccessTokenNotFound {
            get {
                return ResourceManager.GetString("AutoCommitPushAccessTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated update of &quot;{0}&quot;.
        /// </summary>
        internal static string AutoUpdateOfCakeFile {
            get {
                return ResourceManager.GetString("AutoUpdateOfCakeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not the master branch that is checked out.
        /// </summary>
        internal static string CheckedOutBranchIsNotMaster {
            get {
                return ResourceManager.GetString("CheckedOutBranchIsNotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load project &quot;{0}&quot;.
        /// </summary>
        internal static string CouldNotLoadProject {
            get {
                return ResourceManager.GetString("CouldNotLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotUpdate {
            get {
                return ResourceManager.GetString("CouldNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exactly one file to commit and push, got: {0}.
        /// </summary>
        internal static string ExactlyOneFileExpected {
            get {
                return ResourceManager.GetString("ExactlyOneFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no files with uncommitted changes.
        /// </summary>
        internal static string NoFileWithUncommittedChanges {
            get {
                return ResourceManager.GetString("NoFileWithUncommittedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of files with uncommitted changes has changed. Expected {0}, got {1}.
        /// </summary>
        internal static string NumberOfFilesWithUncommittedChangesHasChanged {
            get {
                return ResourceManager.GetString("NumberOfFilesWithUncommittedChangesHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected cake files to commit and push, no other file types.
        /// </summary>
        internal static string OnlyCakeFilesExpected {
            get {
                return ResourceManager.GetString("OnlyCakeFilesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected .csproj and .config files to commit and push, no other file types.
        /// </summary>
        internal static string OnlyCsProjAndConfigFilesExpected {
            get {
                return ResourceManager.GetString("OnlyCsProjAndConfigFilesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find owner and name of the remote repository.
        /// </summary>
        internal static string OwnerAndNameNotFound {
            get {
                return ResourceManager.GetString("OwnerAndNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package/-s updated to most recent version.
        /// </summary>
        internal static string PackageUpdates {
            get {
                return ResourceManager.GetString("PackageUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove repository not found or not unique.
        /// </summary>
        internal static string RemoteNotFoundOrNotUnique {
            get {
                return ResourceManager.GetString("RemoteNotFoundOrNotUnique", resourceCulture);
            }
        }
    }
}
